// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ApplicationFormEvaluatorML.Model
{
    public class ModelInput
    {
        [ColumnName("Result"), LoadColumn(0)]
        public bool Result { get; set; }


        [ColumnName("Text"), LoadColumn(1)]
        public string Text { get; set; }


    }
}
